package com.javalot.ohwoonwan.controller;

import com.javalot.ohwoonwan.domain.*;
import com.javalot.ohwoonwan.repository.*;
import jakarta.annotation.Nullable;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.expression.ExpressionException;
import org.springframework.stereotype.Controller;
import org.springframework.web.ErrorResponseException;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import java.util.Optional;


@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @Autowired
    private PostRepository postRepository;

    @PostMapping(path="/addUser") // Map ONLY POST Requests
    public @ResponseBody String addNewUser (@RequestParam String name, @RequestParam String nickName
            , @RequestParam String email, @RequestParam String phone, @RequestParam String password, @RequestParam Boolean gender ) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        User n = new User();
        n.setName(name);
        n.setNickName(nickName);
        n.setEmail(email);
        n.setPhone(phone);
        n.setPassword(password);
        n.setGender(gender);
        userRepository.save(n);
        return "User Saved";
    }

    @PostMapping(path="/addPost") // Map ONLY POST Requests
    public @ResponseBody String addNewPost (@RequestParam String category, @RequestParam String title
            , @RequestParam String content, @RequestParam Integer createdBy, @RequestParam @Nullable Integer updatedBy ) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Post p = new Post();
        p.setCategory(category);
        p.setTitle(title);
        p.setContent(content);
        User user = userRepository.findById(createdBy).orElseThrow(() -> new ExpressionException("Not found Comment with id = " + createdBy));
        p.setCreatedBy(user);
        if (updatedBy != null) {
            p.setUpdatedBy(user);
        }
        postRepository.save(p);
        return "Post Saved";
    }

    @GetMapping(path="/allUsers")
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }

    @GetMapping(path="/allPosts")
    public @ResponseBody Iterable<Post> getAllPosts() {
        return postRepository.findAll();
    }
}